name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Adjust this to your default branch
  pull_request:
    branches:
      - main  # Adjust this to your default branch

jobs:
  terraform:
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'tf') || github.event_name == 'pull_request' # Adjust if needed
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0 # Adjust to your Terraform version
      
      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

  build-and-deploy:
    runs-on: ubuntu-latest
    # needs: terraform
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t regtech-app:${{ github.sha }} .
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker push regtech-app:${{ github.sha }}

      - name: Copy files to EC2
        env:
          EC2_PRIVATE_IP: ${{ secrets.EC2_PRIVATE_IP }} # Set your EC2 instance's private IP as secret
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Set your SSH private key as a secret
          SSH_USER: "ec2-user" # Adjust if you're using a different user
        run: |
          echo "$SSH_PRIVATE_KEY" > regtech.pem
          chmod 600 regtech.pem
        
          scp -i regtech.pem -o StrictHostKeyChecking=no deployment/deployment.yaml deployment/service.yaml ec2-user@$EC2_PRIVATE_IP:/home/ec2-user/

      - name: Run Deployment on EC2
        env:
          EC2_PRIVATE_IP: ${{ secrets.EC2_PRIVATE_IP }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: "ec2-user"
        run: |
          echo "$SSH_PRIVATE_KEY" > regtech.pem
          chmod 600 regtech.pem
        
          ssh -i regtech.pem -o StrictHostKeyChecking=no ec2-user@$EC2_PRIVATE_IP << 'EOF'
            kubectl apply -f /home/ec2-user/deployment.yaml
            kubectl apply -f /home/ec2-user/service.yaml
          EOF
